# Generated by Django 2.2.5 on 2019-12-17 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0011_auto_20191217_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_like',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 11, 11, 58, 871577, tzinfo=utc)),
        ),
    ]
