# Generated by Django 2.2.5 on 2019-12-25 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0017_auto_20191225_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic_nr',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 18, 23, 44, 857188, tzinfo=utc)),
        ),
    ]
