# Generated by Django 2.2.5 on 2019-12-25 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0021_auto_20191225_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 18, 35, 5, 832033, tzinfo=utc)),
        ),
    ]
