# Generated by Django 2.2.5 on 2019-12-25 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0022_auto_20191225_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic_nr',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 18, 36, 43, 733616, tzinfo=utc)),
        ),
    ]
