# Generated by Django 2.2.5 on 2019-12-27 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0034_auto_20191227_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='valverde.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_nr',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 17, 1, 8, 501847, tzinfo=utc)),
        ),
    ]
