# Generated by Django 2.2.5 on 2019-12-27 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valverde', '0035_auto_20191227_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_nr',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 17, 31, 49, 41536, tzinfo=utc)),
        ),
    ]
